#!/usr/bin/env bash
# Pull Postgres variables from Railway CLI and write a local .env for GlassBase.
# Prerequisites: `railway link` in this repo (Postgres service).
#
# Usage:
#   ./scripts/sync-env-from-railway.sh
#   RAILWAY_POSTGRES_SERVICE=Postgres ./scripts/sync-env-from-railway.sh
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

SERVICE="${RAILWAY_POSTGRES_SERVICE:-Postgres}"
JSON="$(railway variables --json -s "$SERVICE")"

PUB="$(echo "$JSON" | jq -r '.DATABASE_PUBLIC_URL')"
INT="$(echo "$JSON" | jq -r '.DATABASE_URL')"
if [[ -z "$PUB" || "$PUB" == "null" ]]; then
  echo "error: DATABASE_PUBLIC_URL missing from Railway service '$SERVICE'" >&2
  exit 1
fi

OUT="$ROOT/.env"
{
  echo "# Generated by scripts/sync-env-from-railway.sh (service: $SERVICE)"
  echo "# Re-run after Railway credential rotation."
  echo ""
  echo "# Connect from your machine (public proxy; includes TLS):"
  echo "DATABASE_URL=$PUB"
  echo ""
  echo "# On-Railway internal URL (not reachable from laptop; for reference only):"
  echo "# DATABASE_URL_INTERNAL=$INT"
  echo ""
  echo "# Discrete vars (optional; useful for psql / GUIs):"
  echo "PGUSER=$(echo "$JSON" | jq -r '.PGUSER')"
  echo "PGPASSWORD=$(echo "$JSON" | jq -r '.PGPASSWORD')"
  echo "PGDATABASE=$(echo "$JSON" | jq -r '.PGDATABASE')"
  echo "PGPORT=$(echo "$JSON" | jq -r '.RAILWAY_TCP_PROXY_PORT // .PGPORT')"
  echo "PGHOST=$(echo "$JSON" | jq -r '.RAILWAY_TCP_PROXY_DOMAIN // ""')"
  echo ""
  echo "# --- App (not on Postgres; set here or sync from your app service) ---"
  echo "ANTHROPIC_API_KEY="
  echo "APP_ENV=development"
  echo "ANTHROPIC_MODEL=claude-sonnet-4-20250514"
  echo "MAX_CONCURRENT=5"
  echo "HTTP_ADDR=:8080"
  echo "GLASSBASE_RUN_NOW=false"
  echo "POOL_TUNED=false"
} >"$OUT"

echo "Wrote $OUT"
echo "Next: set ANTHROPIC_API_KEY in .env (or run: railway variables -s <your-go-app-service>)"
